### ISSUE TITLE
I am trying to execute the GNNUnlock following all the instructions. Unfortunately, I am stuck with this error when executing the final command as provided in the Readme.md.ing 

### ISSUE THREAD

**Issue by akashdeep95** [DfX-NYUAD/GNNUnlock#3]
(myenv) akashdeep@akashdeep-HP-Notebook:~/GNNUnlock-main/GraphSAINT$ python -m graphsaint.tensorflow_version.train --data_prefix ../Netlist_to_graph/Circuits_datasets/ANTI_SAT_DATASET_c7552/ --train_config ../DATE21.yml --gpu -1 > log_training.txt
/home/akashdeep/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/akashdeep/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/akashdeep/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/akashdeep/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/akashdeep/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/akashdeep/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/home/akashdeep/anaconda3/envs/myenv/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/akashdeep/anaconda3/envs/myenv/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/akashdeep/GNNUnlock-main/GraphSAINT/graphsaint/tensorflow_version/train.py", line 244, in <module>
    tf.app.run(main=train_main)
  File "/home/akashdeep/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/akashdeep/GNNUnlock-main/GraphSAINT/graphsaint/tensorflow_version/train.py", line 237, in train_main
    train_params,train_phases,train_data,arch_gcn = parse_n_prepare(args_global)
  File "/home/akashdeep/GNNUnlock-main/GraphSAINT/graphsaint/utils.py", line 137, in parse_n_prepare
    train_data = process_graph_data(*temp_data)
  File "/home/akashdeep/GNNUnlock-main/GraphSAINT/graphsaint/utils.py", line 92, in process_graph_data
    class_arr[k][v-offset] = 1
IndexError: index 69468 is out of bounds for axis 0 with size 69468

**Comment by lilasrahis** [comment]
I have noticed that you are using --data_prefix ../Netlist_to_graph/Circuits_datasets/ANTI_SAT_DATASET_c7552/.

 It should be --data_prefix ../Netlist_to_graph/Graphs_datasets/anti_sat_iscas_c7552

**Comment by akashdeep95** [comment]
Dear Lilas, thanks for the reply. 
However, I am stuck with the same error even with the modifications suggested by you. I am attaching the error logs for your ref.

$ python -m graphsaint.tensorflow_version.train --data_prefix ../Netlist_to_graph/Graphs_datasets/anti_sat_iscas_c7552 --train_config ../DATE21.yml --gpu -1 > log_training.txt
/home/akashdeep/anaconda3/envs/gnn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/akashdeep/anaconda3/envs/gnn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/akashdeep/anaconda3/envs/gnn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/akashdeep/anaconda3/envs/gnn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/akashdeep/anaconda3/envs/gnn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/akashdeep/anaconda3/envs/gnn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/akashdeep/GNN/GraphSAINT/graphsaint/utils.py:112: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  train_config = yaml.load(f_train_config)
Traceback (most recent call last):
  File "/home/akashdeep/anaconda3/envs/gnn/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/akashdeep/anaconda3/envs/gnn/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/akashdeep/GNN/GraphSAINT/graphsaint/tensorflow_version/train.py", line 244, in <module>
    tf.app.run(main=train_main)
  File "/home/akashdeep/anaconda3/envs/gnn/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/akashdeep/GNN/GraphSAINT/graphsaint/tensorflow_version/train.py", line 237, in train_main
    train_params,train_phases,train_data,arch_gcn = parse_n_prepare(args_global)
  File "/home/akashdeep/GNN/GraphSAINT/graphsaint/utils.py", line 137, in parse_n_prepare
    train_data = process_graph_data(*temp_data)
  File "/home/akashdeep/GNN/GraphSAINT/graphsaint/utils.py", line 92, in process_graph_data
    class_arr[k][v-offset] = 1
IndexError: index 69468 is out of bounds for axis 0 with size 69468

**Comment by cynthi8** [comment]
Make sure your `Netlist_to_graph/Circuits_datasets/ANTI_SAT_DATASET_c7552` folder **only** contains the .bench files. I had some extra files in there and saw the same exact index out of bounds error.
